name: develop-push-workflow
on:
  push:
    branches:
      - develop
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:v2
          php-version: '8'

      - name: Install project dependencies
        run: composer install

      - name: Run php lint on SRC
        run: php -l src -q

      - name: Run php lint on PHPUnit Tests
        run: php -l tests -u

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit -c phpunit.xml